hanshulll/CodeCollection

CollegePortal.java
Created this basic college portal to demonstrate the use of array of Objects.
Thank you
=> Added Basic College Portal

PYTHON/chineseRemainder.py
added a basic python implementation of chinese remainder theorem based on Euclidean division.
=> added chinese remainder theorem

JAVA/SquareWithoutOperator.java
Hey @hanshulll!
I have added the Java code to __'Find the square of a number without using the multiplication operator or the pow function.'__
Please add the `hacktoberfest` tag if you merge the PR.
=> Added square of an integer without * operator (Java)

PYTHON/word_cloud_generator.py
Its a code that creates a image of words where their size depends on frequency of that word in the input
=> Added WordCloud Generator

JAVA/BubbleSort.java
Optimized code of bubble sort.
=> bubble_sort in java language. #Hacktoberfest2021

C++/dnf_sort.cpp
I have added DNF SORT(Dutch National Flag) sort algorithm and I hope it will help others.
=> added dnf sort

C++/odd_gcd.cpp
=> Added sol of BININVER problem

JAVA/hourglass_pattern.java
This will enhance knowledge of for loops
This is my first PR in open source world.I really wish it to get merged! Thanks for the opportunity
=> I have coded a  hourglass pattern in java 

JAVA/radialboundary.java
It'll give me immense motivation to start my journey of open source with this. Thank you for the opportunity.
=> First open source PR->Radial Boundary code

JAVA/Tower_of_hanoi.java
Code in java for the Tower of hanoi problem in recursion
=>  Tower_of_hanoi.java

JAVA/prim.java
According to code, you get this type of result
=> created prims algorithm code

PYTHON/Tower of hanioi.py
=> Create Tower of hanioi.py

README.md
Hi, Happy HacktoberFest 
I have added a package for Design pattern and started with singleton.
=> Design Pattern

JAVA/Expression.java
This will gives output of different expression using 3 variables in Java program.
=> Different expression of 3 variables Java

C/BinarySearchIfElse.c, C/BinarySearchRecursion.c, C/DoublyLinkedList.c, C/PolynomialCalculation.c, C/Queue from stack.c, C/SingleLinkedList.c, C/Stacks.c, C/readme.md, C/sparsematrix.c
Please accept this request and add the hacktober title! Thanks in advance!
=> Data structure implementations using C

JAVA/XPalindromesOfString.java
=> checking palindrome front and from back at X distance

JAVA/FightForHokage.java
A simple brainstorming question!
=> Fight for hokage

JAVA/StackArray.java
I implemented a stack array algorithm using Java language. Please check and accept my PR.
=> implemented stack array algorithm using Java language

Go/keyboardInput.go
Simple program to get keyboard input and display in the terminal.
source : https://golang.org/
=> Program to get keyboard input using Go

RemoveDuplicateFromArray.java
This is a Java program to Remove the Duplicate Elements from an array , please merge my request.
=> Remove Duplicate Element From Array Code

C++/trappingRainWater.cpp
Hi, I have added the famous rainwater trapping problem in C++. as in issue #1 .
=> Feat: C++: Trapping Rainwater Problem

C/Heap sort .c, PYTHON/tictactoe.py
sample output
Enter the number of elements: 4
Enter 4 number of elements: 5
4
6
8
Before sorting the elements are: 5 4 6 8
After sorting the elements are: 4 5 6 8
=> Create Heap sort .c

C++/01Knapsack.cpp, C++/LCS.cpp, C++/MCM.cpp, C++/allPossibleWays.cpp, C++/coinChange.cpp, C++/coinTower.cpp, C++/editDistance.cpp, C++/fibonacci.cpp, C++/friendsPair.cpp, C++/longestIncreasingSubsequence.cpp, C++/lootHouses.cpp, C++/maximizeCutSegments.cpp, C++/minCostPath.cpp, C++/minCountofSquares.cpp, C++/minStepsTo1.cpp, C++/nthCatalanNumber.cpp, C++/numOfBalancedBT.cpp, C++/permutationCoefficient.cpp, C++/shortestSubsequence.cpp, C++/squareMatrixWithZeroes.cpp, C++/staircase.cpp
Dynamic Programming Problems List which I added -
01Knapsack.cpp
editDistance.cpp
longestIncreasingSubsequence.cpp
minCostPath.cpp
numOfBalancedBT.cpp
staircase.cpp
allPossibleWays.cpp
fibonacci.cpp
lootHouses.cpp
minCountofSquares.cpp
permutationCoefficient.cpp
coinChange.cpp
friendsPair.cpp
maximizeCutSegments.cpp
minStepsTo1.cpp
shortestSubsequence.cpp
coinTower.cpp
LCS.cpp
MCM.cpp
nthCatalanNumber.cpp
squareMatrixWithZeroes.cpp
Please let me know if you want some changes
Please merge this under the `Hacktoberfest` label!
=> Added some DP Problems

JavaScript/add-remove.html
JavaScript program to add or remove contents using angular
=> added add-remove program

C++/CodeChef/Triangle With Angle/README.md, C++/CodeChef/Triangle With Angle/Triangle With Angle.cpp
Hi! I want to contribute, this CodeChef problem solution done by me.
=> Added CodeChef Problem Solved

C++/check_binary_tree_subtree.cpp
Check if a binary tree is subtree of another binary tree
=> Created check_binary_tree_subtree.cpp

JAVA/thirdMaximumElementInArray
Code to find third maximum element in an array using java
=> thirdmaximumelementinarray.java

C++/connect_n_ropes_min_cost_priority_queue.cpp
Connect n ropes with minimum cost
=> Created connect_n_ropes_min_cost_priority_queue.cpp

JAVA/FindFirstandLastPositionofElementinSortedArray.java
This is my java Code for Find First and Last Position of Element in Sorted Array - Medium level Leetcode Question. Please check it
=> FirstandLastElement

C++/Codechef/Diagonal Movement.md, C++/Codechef/Diagonal movement code.cpp
I've added the code for the problem Diagonal Movement which was a Starters 14 CodeChef problem. Please review and merge it @hanshulll sir.
=> Added a CodeChef Starters problem

C++/Insertion sort.cpp
I am a beginner to open source contribution . Thank you and I have added insertion sort.cpp under the label hacktoferbest. Please accept the PR. Will also star your repo!!
=> Added insertion sort

PYTHON/Sum_of_n_number_recursion.py
I just added an simple python program for find the sum of n number using recursion 
HAPPY HACKTOBER-FEST!
=> An simple python program was added

C++/RadixSort.cpp
=> added Radix sort

PYTHON/Countdown Timer.py
I have created this timer. Please merge my request. Let me know for any issues.
=> Create Countdown Timer.py

CodeForces/Round 744 (div-3)/A.cpp, CodeForces/Round 744 (div-3)/B.cpp, CodeForces/Round 744 (div-3)/E1.cpp
I added the solutions for Codeforces round 744 
username : dattebayo6172
=> Codeforces Round 744 solutions

PYTHON/calculator(GUI).py
=> Added GUI Calculator

C#/Queue.cs, C#/Stack.cs
Added stack and queue implementation in C#
=> Added Stack and Queue implementation in C#

HappyNumber.py, PYTHON/HappyNumber.py
A Python program to check a number is Happy Number or not
=>  HappyNumber.py

C++/flattenABinaryTree.cpp
I have written a code to flatten a binary tree in C++. please check it out and merge it
=> Flatten A Binary Tree

JAVA/NonDupArray.java
this program is not insert duplicate elements in to the array
=> non duplicate array

PYTHON/screw_your_friends.py
=> screw_your_friends.py

C++/detect_loop_linked_list.cpp
C++ program to return first node of loop
=> Added detect_loop_linked_list.cpp

JAVA/lychrel.java
Lychrel Number program in Java.
=> Lychrel number

C++/totalunorderedwaysofcoinchange.cpp
Hey adding the solution for total unordered ways of coin change problem.
Hope this helps :)
=> Added total unordered ways of coin change

PYTHON/IP-Address-Checker.py
Created a IP Address Checker using Python Programming
=> IP-Address Checker

JAVA/Dijkstra.java, JAVA/Topological_Sort.java
Written the JAVA code for performing topological sort on graph using DFS Algorithm.
=> Added JAVA code for Topological Sort

C++/LinkedList_AppendNode.cpp
Add a node in a Linked List CPP
=> Add a node in a Linked List CPP

C++/equalSumPartition.cpp
Hi, I have added the Partition Array Into Three Parts With Equal Sum. LeetCode 1013
=> Feat: Partition Array Into Three Parts With Equal Sum

JAVA/LinkedList/CheckLLPalindrome
To check whether the given LinkedList is palindrome or not.
=> Added a java program 

C++/burningTree.cpp
I have written a code to Burn a binary tree from node in C++. please check it out and merge it
=> Burning Tree Problem

JAVA/SortColor.java
Added SortColor Code in Java Folder 
Please check this out :)
@hanshulll
=> Added sort the color code in Java

CodeForces/Round 744 (div-3)/E2.cpp
=> Created E2.cpp in Codeforces

JAVA/ValidSquare.java
This .java file contains the solution of LeetCode problem Valid Square.
=> Created ValidSquare.java file

C++/Sieve_of_Eratosthenes.cpp
=> Sieve of Eratosthenes

C++/code subset_sum_dp.cpp
Given an array of non-negative integers and a value sum, determine if there is a subset of the given set with sum equal to given sum.
=> New code subset_sum_dp.cpp

C++/Crossword.cpp
i solved the crossword problem using backtracking in cpp.
=> crossword problem solved using backtracking

C++/Bucket_Sort.cpp
I have created a BUCKET_SORTING algorithm in C++.
=> Bucket_Sort.cpp

C++/ds_avl.cpp
Added program for insertion & deletion in AVL tree
=> Added program for insertion & deletion in AVL tree

C++/LongestIncreasingSubsequence.cpp, C++/ShortestCommonSupersequence.cpp
=> LongestIncreasingSubsequence.cpp

C++/Sliding_window_Maximum.cpp
Added Sliding_window_Maximum.cpp
=> Sliding_window_Maximum.cpp

C++/Pascals_Triangle.cpp
=> Cpp code for Pascal's Triangle

C++/Longest_Increasing_Subsequence.cpp
Longest_Increasing_Subsequence.cpp
=> Longest_Increasing_Subsequence.cpp

C/CircularLinkedList.c
Implementation of Circular Linked List that includes insertion and deletion from the beginning, middle or end.
=> Added implementation of Circular Linked List

C++/Sum_tree.cpp
#1 Solution to the program to check whether a given binary tree is a sum tree or not.
=> Added Sum_tree.cpp

C++/Iterative Deepening Depth First Search.cpp
Added Iterative Deepening Depth First Search in C++ by aakash345
=> Added IDDFS in C++

C++/Binary Indexed Tree.cpp
Added BIT tree code in c++ language
=> Create Binary Indexed Tree.cpp

C++/Transform_to_Sum_tree.cpp
#1 Solution to the program to transform a given binary tree to its sum tree.
=> Added Transform_to_Sum_tree.cpp

C/fibonacci_iterative.c, HackeRank/Java/Java Anagrams/Solution.java, HackeRank/Java/Java Static Initializer Block/Solution.java
Solutions for Java problems:
-static initializer
-Anagram
=> Solutions for hackerrank java problems + fibbonacci series using c 

C++/Data Structure - ADTs/Find Middle_LinkedList.cpp, C++/reversestack.cpp
Added
1) Find Middle Element in a Linked List
2) Reverse a Stack
=> Add C++ DSA codes

C++/majorityvotealgo.cpp
Please approve my  PR I have added Majority Voting Algorithm
=> Added Majority Vote Algorithm

C++/Invert_Binary_Tree.cpp
Hey, I have written this program to invert a binary tree, feel free to merge the request if you feel this is fine for your repo. 
Thanks
=> Invert_Binary_Tree.cpp

PYTHON/Digital_Clock_with_python.py
Made a digital clock using intermediate Python
=> Digital Clock Using Python

Go/SimpleWebServer.go
=> Creating a Basic Web Server

PYTHON/Binary_Search.py
Code for Binary Search in Python
=> Added Binary Search Code in Python

C++/CodeChef/Digit_removal.cpp
This is the solution to the problem which is in October Long challenge 2021 named Digit Removal
=> Digit Removal Problem solution in CPP

C/Factorial.c
Code to find the factorial of a number.
=> Factorial in C

C/Krushkals_algotithm.c
Added a Krushkal Algorithm Program
=> Krushkals Algorithm

PYTHON/audiobook.py, PYTHON/bar_code_creater.py, PYTHON/google_map.py, PYTHON/text_to_sound.py
In this pull request i have added below codes:
- Bar code creator program
- google map creater program
- audio book reader program
- text to speech program
=> Python Projects

LeetCode/rage-sum-quey-mutable.cpp
=> Range Query Mutable

LeetCode/target_sum.cpp
Plz check and merge my Pull Request
=> Solved the Target Sum Problem of LeetCode

JAVA/JewelAndStone.java
hi there!
i add jewel and stone code challenge solution and hope you accept my pull request. thanks you!
=> add jewel and stone

C++/jump-game.cpp
Leetcode link: https://leetcode.com/problems/jump-game/
=> Added solution for jump game (C++)

C/fcfs.c
This file contains the C program for First Come First Serve Algorithm for CPU Scheduling
=> Added fcfs.c

JAVA/MultipleInputs.java
Hope you'll like my contribution 😀
I am a hacktoberfest participant. It would be great if you could merge this PR and mark it as hacktoberfest-accepted.
Thanks 😁
=> Added MultipleInputs code in Java folder

C++/Swap.cpp
implementation of swap two numbers
=> swap two numbers

JAVA/ZigZag_Tree.java, JAVA/kReverse.java
I've Added two codes of Java Programming Language.
One is kReverse Code of Linked Lists and another one is the ZigZag Tree Code of Binary Trees.
=> Added Codes

C/message_encrypter.c
Enter a key of 26 distict alphabets while running the program. Enter the message to be encrypted when prompted. The program while encrypt the message using the key provided and will display the encrypted message.
=> Added message encrypter project

C++/Roman.cpp
=> Numbers to Roman Numerals

PYTHON/whatsappBot.py, PYTHON/wifi_info.py
Get WIFI information and password
=> WIFI Information

PYTHON/whatsappBot.py
=> WhatsApp demo added

C++/merge_arrays.cpp
The program merges k sorted arrays into one
=> Program in C++

C++/nCr_combinations.cpp
This program prints combination of groups of r in total of n.
=> added nCr_combinations.cpp

C++/CoinGames/PredictWinner.cpp, C++/CoinGames/TossCoin.cpp
2 new Coin games are added in the file, name CoinGames.
=> new Coin Game

C++/SpiralMatrix.cpp
Complexity Analysis: 
Time Complexity: O(m*n). 
To traverse the matrix O(m*n) time is required.
Space Complexity: O(1). 
No extra space is required.
=> Print a matrix in spiral form.

C++/Data Structure - ADTs/BasicLinkedList.cpp
This is Basic linked list in opp.
=> BasicLinkedList

JAVA/StringReverse.java
Hi Team,
Added Java Code for reversing a String. 
Kindly check the PR and merge the code.
Regards,
Manoj Karthick
=> Added Java Code for reversing a String

JavaScript/newton.js
Newton-Raphson square root formula with JavaScript.
=> Newton Square root Solution

LeetCode/Length Of Last Word/LengthOfLastWord.cpp, LeetCode/Length Of Last Word/README.md, LeetCode/Merge Two Sorted Lists/MergeTwoSortedLists.ts, LeetCode/Merge Two Sorted Lists/README.md, LeetCode/Plus One/PlusOne.ts, LeetCode/Plus One/README.md
Solutions for 3 Leetcode problems have been added.
1. Plus One _(in Typescript)_
2. Merge Two Sorted Lists _(in Typescript)_
3. Length of Last Word _(in C++)_
=> Leetcode: 3 solutions added

LeetCode/1137. N-th Tribonacci Number.cpp
=> Solved LeetCode 1137. N-th Tribonacci Number

C++/Data Structure - ADTs/StackWithArray.cpp
Hey @hanshulll  I have added StackWithArray program
=> Added StackWithArray

HackeRank/Sherlock and MiniMax.cpp
Added a new .cpp file for sherlock n minimax coding
=> Created CPP Code for Sherlock n MiniMax

LeetCode/222. Count Complete Tree Nodes.cpp
Medium difficulty 
Hacktoberfest 2021
Kindly approve and merge
=> Solved  222. Count Complete Tree Nodes in Cpp

Go/readWriteRecordsToFile.cpp
A C++ program that uses the fstream stream library to write records to a file, read records from a file and to delete the made file as well.
=> To write and read records from a file and to delete a file aswell

PYTHON/phonenumbers.py
I have added phone numbers file in python, kindly review it and please add it.
=> Phone numbers file in python.

C/Matrix multiplication.c, C/palindrome.c
Check a Numbere is Palindrome or Not using C Language
=> Check a Numbere is Palindrome or Not

C++/Set Matrix Zeroes.cpp
=> Create a set matrix zero leetcode problem

C/shellsort.c, JAVA/prime-number-checker.java
HI ! here I have added the Shell Sort Algorithm.. will you please review it and merge it
=>  Adding shellsort algorithm

C#/Sorting-list-using-c#.cs
Hey @hanshulll please merge my pull request. This will really boost my confidence. I'm participating Hacktoberfest for the first time. please merge my pull request
=> Sorting List in C#

php/line_notify.php
=> added line_notify.php

JAVA/PostOrderTarversalUsingIteration.java
Program to Post Order Traversal Using Iterative Approach
=> Post Order Traversal Using Iteration

JAVA/GUI-Calculator.java
A simple GUI Calculator created in Java.
=> Added GUI-Calculator.java

C++/calculator_using_switch.cpp
=> useful commit message

C++/spiral_matrix.cpp
Added spiral matrix problem using cpp
Time Complexity : O(NxM)
=> Added spiral matrix problem using cpp

C++/Codechef_OCT21C_MEXOR.cpp
I have added code(solution) to October challenge MEXOR problem.
Problem Code: MEXOR
Problem Link : https://www.codechef.com/OCT21C/problems/MEXOR
=> Added code(solution) to October challenge MEXOR problem

CodeChef/CHAPTER'S APPETIZER 26-09-2021/Queries in an Array.cpp
Queries in an Array
Chef has an array A consisting of positive integers. This array is sorted in non-decreasing order from left to right.
You are given Q queries. Each query consists of three integers l, r, x. Answer of this query can be found as follows. Consider the sub array al, al+1… ar. The answer to the query is the count of numbers in this sub array that are greater or equal to x.
Input
•	The first line of each test case contains two space-separated integers n, Q.
•	The second line contains n space separated integers denoting the array A.
•	Each of the next Q lines contains three space-separated integers l, r, x denoting the query.
Output
Output Q lines one for each query containing the answer for the corresponding the query.
Constraints
•	1 ≤ n,Q ≤ 10^5 
•	1 ≤ ai ≤ 10^9
•	1≤ l ≤ r …
=> CHAPTER'S APPETIZER 26-09-2021

C++/N-th_Tribonacci_Number.cpp, C++/n_queens.cpp
Dynamic Programming Memoization method has been used. Time complexity : O(N)
=> N-th Tribonacci number

LeetCode/Intersection of Two Linked Lists/intersection-of-two-linked-lists.cpp
Solved question 160. Intersection of Two Linked Lists
Hacktoberfest 2021
=> Solution of 160. Intersection of Two Linked Lists

C++/randomized_quicksort.cpp
Code for randomized quicksort added
Pivot is randomly selected using random  function.
=> randomized quicksort added

HackeRank/SQL/type_of_triangle.sql
Added a SQL code for Hacker Rank Type of Triangle problem
=> Added a Hacker Rank - SQL - Type of Triangle

C++/HollowRhombusPattern.cpp
:)
Enjoy the fascinating pattern! 👍
=> HollowRhombusPattern.cpp

C++/Data Structure - ADTs/DuplicateElements.cpp
Added solution to Duplicate Elements problem.
=> Create Solution for DuplicateElements

LeetCode/SetMatrixZeroes.cpp
The code with explanation of each line is given in the file.
=> Set Matrix Zeroes , LeetCode 73

C/Calculator.c
A simple Calculator created in C Language.
=> Added Calculator.c

JavaScript/JS_table/index.html, JavaScript/JS_table/script.js, JavaScript/JS_table/style.css
=> table JS added

C++/First_negative_number.cpp
* What is this PR about 
Created a program on First negative number in array of size K usiing c++
It is based on the concept of sliding window algorithm
=> added first_negative_number code in C++

CSES/Graph_Algorithms_Labyrinth.cpp
Problem Link - https://cses.fi/problemset/task/1193/
=> Adding Graph_Algorithms_Labyrinth.cpp to CSES
